---
title: "WES Report"
author: "Stephen Kelly"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    css: styles.css
    keep_md: yes
    number_sections: true
    toc: true
    toc_float: true
params:
  run_analysis_output_dir: run_analysis_output
  sns_wes_coverage_analysis_dir: sns-wes-coverage-analysis
---
<!-- Setup the R code to be used in R Markdown generation throughout the report -->
```{r setup, include=FALSE} 
# {.tabset} # .tabset-fade .tabset-pills

# ~~~~~ SETTINGS ~~~~~ #
knitr::opts_chunk$set(echo = FALSE)

# ~~~~~ LOAD PACKAGES ~~~~~ #
library("knitr")
library("ggplot2")
library("reshape2")
library("data.table")
library("DT")
# ~~~~~ CUSTOM FUNCTIONS ~~~~~ #
mycat <- function(text){
    # function for formatting text in the report
    cat(gsub(pattern = "\n", replacement = "  \n", x = text))
}

reindex_rownames <- function(df){
    # reindex the row names after subsetting
    if(nrow(df) > 0) rownames(df) <- seq(nrow(df))
    return(df)
}
# ~~~~~ LOAD REPORT DATA ~~~~~ #
report_dir <- getwd() # setwd(report_dir)
sns_wes_coverage_analysis_dir <- params$sns_wes_coverage_analysis_dir
run_analysis_output_dir <- params$run_analysis_output_dir
summary_combined_table_file <- file.path(run_analysis_output_dir, "summary-combined.wes.csv")

summary_combined_table <- read.delim(file = summary_combined_table_file, sep = ',')
setnames(x = summary_combined_table, old = c("X.SAMPLE"), new = c("sample"))

save.image(file="load_report_data.Rdata",compress = TRUE)
```

```{r, samples_table}
samples_df <- summary_combined_table[, "sample", drop = FALSE]
```

```{r, mapping_table}
mapping_table <- summary_combined_table[, "sample", drop = FALSE]
# mapping_table["avg_raw_reads"] <- as.numeric(summary_combined_table[["R1.RAW.READS"]]) + as.numeric(summary_combined_table[["R2.RAW.READS"]]) / 2
mapping_table["mapped"] <- summary_combined_table[["MAPPED.READS"]]
mapping_table["deduplicated"] <- summary_combined_table[["DEDUPLICATED.READS"]]

mapping_table <- reshape2::melt(mapping_table,id.vars="sample",variable.name="type",value.name="reads")

mapping_table[["reads"]] <- mapping_table[["reads"]] / 1e6

mapping_table[["type"]] <- factor(x = mapping_table[["type"]], levels = sort(unique(as.character(mapping_table[["type"]]), decreasing = TRUE)))

mapping_plot <- ggplot(data = mapping_table, aes(x = sample, y = reads, fill = type)) + geom_bar(stat="identity", position = "dodge") + ggtitle("Sample Read Mapping") + coord_flip() + ylab("reads (millions)")  # 

```

```{r, coverage_cutoffs}
# colnames of the coverage cutoff columns
coverage_above_cols <- c("X._bases_above_10", "X._bases_above_50", "X._bases_above_100", "X._bases_above_500")

# make a table for just the coverage cutoff data
coverage_cutoff_table <- reshape2::melt(summary_combined_table[c("sample", coverage_above_cols)],id.vars="sample",variable.name="coverage_cutoff",value.name="percent")

# fix the values in the cutoff column
coverage_cutoff_table[["coverage_cutoff"]] <- gsub(pattern = 'X._bases_above_', replacement = '', x = as.character(coverage_cutoff_table[["coverage_cutoff"]]))
# reorder the factor levels for the plot
coverage_cutoff_table[["coverage_cutoff"]] <- factor(coverage_cutoff_table[["coverage_cutoff"]], levels = sort(unique(as.numeric(coverage_cutoff_table[["coverage_cutoff"]]))))

# make the plot
coverage_cutoff_plot <- ggplot(data = coverage_cutoff_table, aes(x = sample, y = percent, fill = coverage_cutoff)) + geom_bar(stat="identity", position = "dodge") + ggtitle("Percent of Bases Above Coverage Cutoff") + coord_flip()

```

```{r, low_coverage_regions}
regions_coverage_below_50_annotation_table <- read.delim(file.path(sns_wes_coverage_analysis_dir, "regions_coverage_below_50_annotation.tsv"))


setnames(x = regions_coverage_below_50_annotation_table, old = c("external_gene_name", "seqnames", "gene_biotype"), new = c("gene", "chrom", "biotype"))

regions_coverage_below_50_annotation_table <- regions_coverage_below_50_annotation_table[order(regions_coverage_below_50_annotation_table[["gene"]]),]
regions_coverage_below_50_annotation_table <- reindex_rownames(regions_coverage_below_50_annotation_table)

low_cov_cols <- c("gene", "chrom", "start", "end", "width", "distancetoFeature", "biotype")

```

# Sample Information

```{r, results='asis'}
kable(samples_df, row.names = TRUE, caption = "Samples included in the analysis") # , align = c("c")
# datatable(samples_df, caption = "Samples included in the analysis")

```

## Mapping

```{r, fig.height=12, fig.width=8}
print(mapping_plot)
```

## Coverage

```{r, fig.height=12, fig.width=8}
print(coverage_cutoff_plot)
```

# Target Regions

## Regions With Low Coverage

```{r}
datatable(regions_coverage_below_50_annotation_table[low_cov_cols])
```

# System Information {.tabset .tabset-pills}

## Hide

## Show

```{r}
# system info
system("uname -srv", intern = TRUE)

# dir
system('pwd',intern=T)

# repo info
system('git remote -v',intern=T)
system('printf "%s\t%s" "$(git rev-parse --abbrev-ref HEAD)" "$(git rev-parse HEAD)"',intern=T)

# date time
system("date", intern = TRUE)

# R system info, packages, etc
sessionInfo()

# save current session
save.image(file="final_report_data.Rdata",compress = TRUE)
```
